# Generated by Django 4.0.4 on 2022-05-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btresults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1_Name', models.IntegerField()),
                ('Team2_Name', models.IntegerField()),
                ('Toss_Wining_Team', models.IntegerField()),
                ('Toss_Decision', models.IntegerField()),
                ('Venue', models.CharField(max_length=122)),
            ],
        ),
    ]
