# Generated by Django 4.0.4 on 2022-05-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Btresults',
            new_name='Btresult',
        ),
    ]
