# Generated by Django 4.0.4 on 2022-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_btresults_btresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='btresult',
            name='ans',
            field=models.CharField(default='100', max_length=122),
        ),
        migrations.AlterField(
            model_name='btresult',
            name='Team1_Name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='btresult',
            name='Team2_Name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='btresult',
            name='Toss_Decision',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='btresult',
            name='Toss_Wining_Team',
            field=models.CharField(max_length=122),
        ),
    ]
