# Generated by Django 4.0.4 on 2022-05-15 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_btresult_ans_alter_btresult_team1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btresult',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 15, 12, 53, 294000)),
        ),
    ]
