# Generated by Django 4.0.4 on 2022-05-26 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_btresult_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1_P1', models.CharField(max_length=122)),
                ('T1_P2', models.CharField(max_length=122)),
                ('T1_P3', models.CharField(max_length=122)),
                ('T1_P4', models.CharField(max_length=122)),
                ('T1_P5', models.CharField(max_length=122)),
                ('T1_P6', models.CharField(max_length=122)),
                ('T1_P7', models.CharField(max_length=122)),
                ('T1_P8', models.CharField(max_length=122)),
                ('T1_P9', models.CharField(max_length=122)),
                ('T1_P10', models.CharField(max_length=122)),
                ('T1_P11', models.CharField(max_length=122)),
                ('T2_P1', models.CharField(max_length=122)),
                ('T2_P2', models.CharField(max_length=122)),
                ('T2_P3', models.CharField(max_length=122)),
                ('T2_P4', models.CharField(max_length=122)),
                ('T2_P5', models.CharField(max_length=122)),
                ('T2_P6', models.CharField(max_length=122)),
                ('T2_P7', models.CharField(max_length=122)),
                ('T2_P8', models.CharField(max_length=122)),
                ('T2_P9', models.CharField(max_length=122)),
                ('T2_P10', models.CharField(max_length=122)),
                ('T2_P11', models.CharField(max_length=122)),
                ('Toss_Wining_Team', models.CharField(max_length=122)),
                ('Toss_Decision', models.CharField(max_length=122)),
                ('Venue', models.CharField(max_length=122)),
                ('ans', models.CharField(default='100', max_length=122)),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 27, 0, 47, 16, 488317))),
            ],
        ),
        migrations.AlterField(
            model_name='btresult',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 0, 47, 16, 457060)),
        ),
    ]
