# Generated by Django 4.0.4 on 2022-05-26 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_atresult_alter_btresult_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='atresult',
            name='Team1_Name',
            field=models.CharField(default='100', max_length=122),
        ),
        migrations.AddField(
            model_name='atresult',
            name='Team2_Name',
            field=models.CharField(default='100', max_length=122),
        ),
        migrations.AlterField(
            model_name='atresult',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 1, 37, 10, 378942)),
        ),
        migrations.AlterField(
            model_name='btresult',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 1, 37, 10, 331673)),
        ),
    ]
